### PR TITLE
Update package_generator.dart

### PR DESCRIPTION
**Pull request by devoncarew**
- speculative fix for flutter package generation
 (for https://github.com/astashov/dartdocs.org/issues/47, and from discussion https://github.com/dart-lang/dartdoc/issues/1431)

@astashov

### CODE REVIEW

**Comment by mit-mit** [comment]
I tried this against `firebase_auth`, and looks like we may be missing a few exclusions?

```
documenting firebase_auth
generating docs for library _empty from _empty.dart...
generating docs for library dart._internal from internal.dart...
  warning: 'dart._internal' has no library level documentation comments
generating docs for library firebase_auth from firebase_auth.dart...
Documented 3 libraries in 11.9 seconds.
```

**Comment by devoncarew** [comment]
I think this is due to the copies of the dart: libraries in the flutter sdk (in the dart-sdk/ dir, and in `bin/cache/pkg/sky_engine/lib/`. Those copies in `bin/cache/pkg/sky_engine/lib/` look like regular dart packages to dartdoc, since they're not in the dart sdk.

**Comment by devoncarew** [comment]
The updates to the PR address all the spurious libraries except for `_empty` (which, true to its name, is empty).

This PR works around much of the issue, and https://github.com/dart-lang/dartdoc/issues/1431 tracks the rest of the work (likely, recognizing that these libs are really dart: libraries).

**Comment by mit-mit** [comment]
@devoncarew can we go ahead and merge this?

Also, how do we get dartdoc re-run for all packages after that?

cc @kevmoo

**Comment by astashov** [comment]
Yeah, sorry for delay, LGTM

**Comment by mit-mit** [comment]
Thanks @astashov! Is there a way to trigger a re-run to generate new docs for the [flutter packages](https://pub.dartlang.org/flutter/packages) that are impacted by this?

**Pull request merged**
