### PR TITLE
Some tweaks

### PR DESCRIPTION
**Pull request by kevmoo**
Please take a look, @astashov

### CODE REVIEW

**Comment by astashov** [comment]
Could you please use `-l 120` on `dartfmt`? With 80 it cuts the lines really aggressively. :)
Is there any way to provide some options file for dartfmt? Like `.dartfmt`, which would contain `max_line_length: 120`. To communicate the default settings used in the app.

**Comment by astashov** [comment]
The cool thing about `exit()` - even if I forget about some future (and I definitely could :)), it won't hang waiting til its done but exit immediately. That's why I added them. How that could make debugging hard?

**Comment by kevmoo** [comment]
RE line length: 80 seems small, but we've actually found it really encourages good coding practices – it helps folks avoid long statements or really long strings. It also makes code review easier w/ side-by-side comparisons. We've standardized on 80 across all of our code and tools.

RE exit: exit kills the VM instantly. If you have observatory running and you're debugging a process it'll just die – it doesn't respect "--pause-on-exit".

**Comment by astashov** [comment]
> exit kills the VM instantly. If you have observatory running and you're debugging a process it'll just die – it doesn't respect "--pause-on-exit". 

Is there a way to respect `--pause-on-exit`, but don't wait for all the futures to complete on exit?

**Comment by kevmoo** [comment]
> Is there a way to respect --pause-on-exit, but don't wait for all the futures to complete on exit?

Not that I know. The other option is to throw and have a top-level catch that handles setting the exit code

**Comment by astashov** [comment]
Okay, LGTM. Hopefully `dartfmt` won't break things :)

**Pull request merged**
